#!/usr/bin/env ruby
require 'forever'
require 'fileutils'

Forever.run do
  before :each do
    puts "Running a job"
  end

  every 5.minutes do
    system("ruby '#{File.absolute_path(File.join(File.dirname(__FILE__), "../bin/temperature-logger"))}'")
  end

  every 1.day do
    puts "A Day"
  end
end
